version: "3.7"

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  nest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DATABASE_HOST=database
    volumes:
      - ./src:/app/src
      - ./libs:/app/libs
      
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./database/nest:/var/lib/postgresql/data
