version: "3.7"

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  nest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DATABASE_HOST=database
    volumes:
      - ./src:/app/src
      - ./libs:/app/libs

  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nest
      - MYSQL_ROOT_PASSWORD=test
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/nest:/var/lib/mysql
